import Head from "next/head";
import type { NextPage } from "next";

import styles from "@styles/Home.module.css";
import { Featured } from "@components/ui";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pizza Restaurant in Newyork</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Featured />
    </div>
  );
};

export default Home;
